version: "3"
services:
  oracle11g:
    image: jaspeen/oracle-xe-11g
    container_name: oracle11
    ports:
      - 1521:1521
      - 8080:8080

  spring-docker:
    image: hyegyeongkang/spring-docker
    build: ./spring-docker/spring-docker
    ports:
      - 8000:8000

  vue-spring:
    image: hyegyeongkang/vue-spring 
    build: ./vue-spring
    ports:
      - 8081:8081