server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
<<<<<<< HEAD
    url: jdbc:oracle:thin:@oracle11g:1521:XE
=======
    # ??? ??? ??? ???? ??
    url: # 사용할 DB URL 
>>>>>>> 9e39c61ed58fcb8782bce55fd21efc343a949116
    username: system
    password: oracle

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springdocker.vo

