version: "3"
services:
  oracle11g:
    image: # 
    container_name: oracle
    ports:
      - 1521:1521
      - 8080:8080

  spring-docker:
    image: hyegyeongkang/spring-docker
    build: .
    ports:
      - 8081:8081
